import type { Entity, ImpactTag, Legislation } from "@/types";

import netherlands from "@/data/international/netherlands.json";
import ireland from "@/data/international/ireland.json";
import sweden from "@/data/international/sweden.json";
import finland from "@/data/international/finland.json";
import spain from "@/data/international/spain.json";
import italy from "@/data/international/italy.json";
import poland from "@/data/international/poland.json";
import singapore from "@/data/international/singapore.json";
import india from "@/data/international/india.json";
import taiwan from "@/data/international/taiwan.json";
import indonesia from "@/data/international/indonesia.json";
import australia from "@/data/international/australia.json";
import ontario from "@/data/international/ontario.json";
import quebec from "@/data/international/quebec.json";
import britishColumbia from "@/data/international/british-columbia.json";

/**
 * Auto-generated by scripts/sync/international.ts. Do not edit by hand.
 * Entries come from data/international/*.json. Regenerated after every
 * successful sync run.
 *
 * This file also sanitizes incoming research payloads because Claude
 * sometimes invents impactTags outside our enum — we filter those out
 * rather than let the UI crash on unknown keys.
 */

const VALID_IMPACT_TAGS = new Set<ImpactTag>([
  "water-consumption",
  "carbon-emissions",
  "protected-land",
  "environmental-review",
  "renewable-energy",
  "grid-capacity",
  "energy-rates",
  "water-infrastructure",
  "noise-vibration",
  "local-zoning",
  "local-control",
  "residential-proximity",
  "property-values",
  "tax-incentives",
  "job-creation",
  "economic-development",
  "nda-transparency",
  "algorithmic-transparency",
  "ai-safety",
  "deepfake-regulation",
  "ai-in-healthcare",
  "ai-in-employment",
  "ai-in-education",
  "child-safety",
  "data-privacy",
]);

function sanitizeLegislation(l: Legislation): Legislation {
  return {
    ...l,
    impactTags: (l.impactTags ?? []).filter((t): t is ImpactTag =>
      VALID_IMPACT_TAGS.has(t as ImpactTag),
    ),
  };
}

function sanitizeEntity(e: Entity): Entity {
  return {
    ...e,
    legislation: (e.legislation ?? []).map(sanitizeLegislation),
    keyFigures: e.keyFigures ?? [],
    news: e.news ?? [],
  };
}

const modules: Entity[] = [];
function register(mod: unknown) {
  if (mod && typeof mod === "object" && "id" in (mod as Record<string, unknown>)) {
    modules.push(sanitizeEntity(mod as Entity));
  }
}

register(netherlands);
register(ireland);
register(sweden);
register(finland);
register(spain);
register(italy);
register(poland);
register(singapore);
register(india);
register(taiwan);
register(indonesia);
register(australia);
register(ontario);
register(quebec);
register(britishColumbia);

export const RESEARCHED_INTERNATIONAL: Entity[] = modules;
